### ISSUE TITLE
С др

### ISSUE THREAD

**Issue by penguin-boxx** [kk2342/babka#1]

**Comment by relax2k** [comment]
С Днем Рождения, маленький свинко-гений.
Всегда добивайся своих целей, будь оптимистичен и не обращай внимания на тех, кто упрекает тебя в твоей гениальности.
ну а с питоном да, перебор, посмотри курсы какие нить, что ли.
![image](https://user-images.githubusercontent.com/48926693/75782639-45621e80-5d70-11ea-8af6-0d0c5531353d.png)

**Comment by kk2342** [comment]
> Тебе уже чертова дюжина лет, сколько можно бабок кодировать?
> 
> К тому же на питоне можно писать красиво, например [так](https://gist.github.com/winter-yuki/2e1d1a1af9e78f5bc29fe478493d42be). Учись писать питоняшный код.
> 
> И будь крут как Ван Дамм:
> ![imgpsh_fullsize](https://user-images.githubusercontent.com/25281147/75778317-9cfc8c00-5d68-11ea-9213-746769ac61b2.jpeg)

**Comment by kk2342** [comment]
Спасибо! смотри мой код

**Comment by kk2342** [comment]
спасибо я реально генiй умнее надьки
